/*

    OpenGL loader generated by glad 0.1.36 on Mon Feb  9 02:44:38 2026.

    Language/Generator: C/C++
    Specification: gl
    APIs: gl=3.3
    Profile: compatibility
    Extensions:
        
    Loader: True
    Local files: False
    Omit khrplatform: False
    Reproducible: False

    Commandline:
        --profile="compatibility" --api="gl=3.3" --generator="c" --spec="gl" --extensions=""
    Online:
        https://glad.dav1d.de/#profile=compatibility&language=c&specification=gl&loader=on&api=gl%3D3.3
*/

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wbuiltin-macro-redefined"
#include <glad/glad.h>
#pragma GCC diagnostic pop

PFNGLCLEARPROC glad_glClear;
PFNGLCLEARCOLORPROC glad_glClearColor;
PFNGLENABLEPROC glad_glEnable;
PFNGLDISABLEPROC glad_glDisable;
PFNGLBEGINPROC glad_glBegin;
PFNGLENDPROC glad_glEnd;
PFNGLVERTEX3FPROC glad_glVertex3f;
PFNGLCOLOR3FPROC glad_glColor3f;
PFNGLPOINTSIZEPROC glad_glPointSize;
PFNGLSWAPBUFFERSPROC glad_glSwapBuffers;
PFNGLLOADIDENTITYPROC glad_glLoadIdentity;
PFNGLMATRIXMODEPROC glad_glMatrixMode;
PFNGLMULTMATRIXFPROC glad_glMultMatrixf;
PFNGLSCALEFPROC glad_glScalef;
PFNGLTRANSLATEFPROC glad_glTranslatef;
PFNGLROTATEFPROC glad_glRotatef;
PFNGLPUSHMATRIXPROC glad_glPushMatrix;
PFNGLPOPMATRIXPROC glad_glPopMatrix;
PFNGLVIEWPORTPROC glad_glViewport;
PFNGLGETSTRINGPROC glad_glGetString;

typedef void* (APIENTRYP PFNWGLGETPROCADDRESSPROC_PRIVATE)(const char*);
static PFNWGLGETPROCADDRESSPROC_PRIVATE gladGetProcAddressPtr;

static int open_gl(void) {
#ifdef _WIN32
    static int opened = 0;
    if (opened) return 1;
    {
        OSVERSIONINFOEX osvi;
        BOOL gdi32plat;
        HMODULE hlib = GetModuleHandle(TEXT("opengl32.dll"));
        if (!hlib) return 0;
        gladGetProcAddressPtr = (PFNWGLGETPROCADDRESSPROC_PRIVATE) GetProcAddress(hlib, "wglGetProcAddress");
        if (!gladGetProcAddressPtr) {
            HMODULE hmod = GetModuleHandle(TEXT("gdi32.dll"));
            if (hmod) {
                gladGetProcAddressPtr = (PFNWGLGETPROCADDRESSPROC_PRIVATE) GetProcAddress(hmod, "wglGetProcAddress");
            }
        }
        opened = 1;
        return 1;
    }
#elif defined(__App__)
#endif

    return 1;
}

static void* get_proc(const char *namez) {
    void* result = NULL;
    if (gladGetProcAddressPtr != NULL) {
        result = (void*) gladGetProcAddressPtr(namez);
    }
    if ((result == NULL) && (namez[0] != '_')) {
        int len = (int)strlen(namez);
        char proc[256];
        proc[0] = '_';
        strncpy(proc + 1, namez, len >= 255 ? 254 : len);
        proc[len + 1] = 0;
        result = (void*) gladGetProcAddressPtr(proc);
    }
    return result;
}

int gladLoadGLLoader(GLADloadproc load) {
    open_gl();
    
    glad_glClear = (PFNGLCLEARPROC) load("glClear");
    glad_glClearColor = (PFNGLCLEARCOLORPROC) load("glClearColor");
    glad_glEnable = (PFNGLENABLEPROC) load("glEnable");
    glad_glDisable = (PFNGLDISABLEPROC) load("glDisable");
    glad_glBegin = (PFNGLBEGINPROC) load("glBegin");
    glad_glEnd = (PFNGLENDPROC) load("glEnd");
    glad_glVertex3f = (PFNGLVERTEX3FPROC) load("glVertex3f");
    glad_glColor3f = (PFNGLCOLOR3FPROC) load("glColor3f");
    glad_glPointSize = (PFNGLPOINTSIZEPROC) load("glPointSize");
    glad_glSwapBuffers = (PFNGLSWAPBUFFERSPROC) load("glSwapBuffers");
    glad_glLoadIdentity = (PFNGLLOADIDENTITYPROC) load("glLoadIdentity");
    glad_glMatrixMode = (PFNGLMATRIXMODEPROC) load("glMatrixMode");
    glad_glMultMatrixf = (PFNGLMULTMATRIXFPROC) load("glMultMatrixf");
    glad_glScalef = (PFNGLSCALEFPROC) load("glScalef");
    glad_glTranslatef = (PFNGLTRANSLATEFPROC) load("glTranslatef");
    glad_glRotatef = (PFNGLROTATEFPROC) load("glRotatef");
    glad_glPushMatrix = (PFNGLPUSHMATRIXPROC) load("glPushMatrix");
    glad_glPopMatrix = (PFNGLPOPMATRIXPROC) load("glPopMatrix");
    glad_glViewport = (PFNGLVIEWPORTPROC) load("glViewport");
    glad_glGetString = (PFNGLGETSTRINGPROC) load("glGetString");

    if (!glad_glClear || !glad_glEnable || !glad_glBegin || !glad_glEnd ||
        !glad_glVertex3f || !glad_glColor3f) {
        return 0;
    }
    return 1;
}